### ISSUE TITLE
Error when trying to create random entry

### ISSUE THREAD

**Issue by animaux** [DeuxHuitHuit/random_entries_generator#2]
```
28. May 2015 09:03 > Fatal Error: GenericExceptionHandler 1: Cannot instantiate abstract class Faker\Provider\Text on line 16 of file /…/extensions/random_entries_generator/vendor/fzaninotto/faker/src/Faker/Factory.php
```
- Symphony 2.6.2
- Random Entries Generator 1.1.0
- PHP 5.5.18

**Comment by nitriques** [comment]
Hum this is weird.

Do you have a complete stack ?

**Comment by animaux** [comment]
You mean if the extension is complete? Please elaborate :)

**Comment by nitriques** [comment]
> Do you have a complete stack ?

A call stack... meaning were in the extension code is created that Faker object ...

**Comment by animaux** [comment]
I’m afraid I can’t follow. I’m just a humble designer … o_0

**Comment by nitriques** [comment]
No worries, I am here to help.

Where did you get that error message ? In the logs ?

Or did you had an error page ?

**Comment by animaux** [comment]
Thanks for bearing with me :)

> Where did you get that error message ? In the logs ?

Both, with the same content.

**Comment by nitriques** [comment]
> Thanks for bearing with me :)

No problems!

Are you able to reproduce and give me the complete screenshot of the error page ? The stack trace should be there :) That would help a lot!

**Comment by animaux** [comment]
Ah … THAT stack m( I’m afraid there’s none :(

![bildschirmfoto 2015-05-29 um 17 10 05](https://cloud.githubusercontent.com/assets/446874/7885703/b3785c1a-0625-11e5-9bf7-ab6d3088713f.png)

**Comment by nitriques** [comment]
Damn.....

**Comment by nitriques** [comment]
Looks like a Faker + PHP 5.5.18 bug... Because on PHP 5.3 (do not judge me), it works...

Or maybe it's related to the language... can you try by setting your account as English (if that's not already the case)

Finally, can you try to add a `debug_print_backtrace();die;` on line 15 in the Factory.php file ?

**Comment by animaux** [comment]
Language English: no change.

**Comment by animaux** [comment]
```
  \#0 Faker\Factory::create() called at [/…/~websites/ejbw/extensions/random_entries_generator/lib/class.fieldadapter.php:166]
  \#1 FieldAdapter::faker() called at [/…/~websites/ejbw/extensions/random_entries_generator/lib/generators/class.textgenerator.php:26]
  \#2 TextGenerator::generate(Array ([max-length] => 80)) called at [/…/~websites/ejbw/extensions/random_entries_generator/lib/adapters/class.inputfieldadapter.php:26]
  \#3 InputFieldAdapter->data(Section Object ([] => Array ([id] => 11,[name] => Aktuelles,[handle] => aktuelles,[sortorder] => 7,[hidden] => no,[max_entries] => 0,[filter] => yes,[navigation_group] => Inhalte)), FieldInput Object ([] => 0,[] => Array ([required] => yes,[show_column] => yes,[id] => 83,[label] => Titel (de),[element_name] => titel-de,[type] => input,[parent_section] => 11,[sortorder] => 1,[location] => main,[field_id] => 83,[validator] => ),[] => 1,[] => 1,[] => ,[_handle] => input,[_name] => Text Input)) called at [/…/~websites/ejbw/extensions/random_entries_generator/lib/class.fieldadapter.php:70]
  \#4 FieldAdapter->generateData(Section Object ([] => Array ([id] => 11,[name] => Aktuelles,[handle] => aktuelles,[sortorder] => 7,[hidden] => no,[max_entries] => 0,[filter] => yes,[navigation_group] => Inhalte)), FieldInput Object ([] => 0,[] => Array ([required] => yes,[show_column] => yes,[id] => 83,[label] => Titel (de),[element_name] => titel-de,[type] => input,[parent_section] => 11,[sortorder] => 1,[location] => main,[field_id] => 83,[validator] => ),[] => 1,[] => 1,[] => ,[_handle] => input,[_name] => Text Input)) called at [/…/~websites/ejbw/extensions/random_entries_generator/content/content.create.php:65]
  \#5 contentExtensionRandom_entries_generatorCreate->createRandomEntries() called at [/…/~websites/ejbw/extensions/random_entries_generator/content/content.create.php:23]
  \#6 contentExtensionRandom_entries_generatorCreate->__viewIndex() called at [/…/~websites/ejbw/symphony/lib/toolkit/class.administrationpage.php:705]
  \#7 AdministrationPage->__switchboard() called at [/…/~websites/ejbw/symphony/lib/toolkit/class.administrationpage.php:655]
  \#8 AdministrationPage->view() called at [/…/~websites/ejbw/symphony/lib/toolkit/class.administrationpage.php:465]
  \#9 AdministrationPage->build(Array ()) called at [/…/~websites/ejbw/symphony/lib/core/class.administration.php:212]
  \#10 Administration->__buildPage(/extension/random_entries_generator/create/) called at [/…/~websites/ejbw/symphony/lib/core/class.administration.php:490]
  \#11 Administration->display(/extension/random_entries_generator/create/) called at [/…/~websites/ejbw/symphony/lib/boot/func.utilities.php:232]
  \#12 symphony_launcher(administration) called at [/…/~websites/ejbw/symphony/lib/boot/func.utilities.php:212]
  \#13 symphony(administration) called at [/…/~websites/ejbw/index.php:17]
```

**Comment by animaux** [comment]
Hope this is any help. Have to get going now, will only be able to catch on on monday. Cheers!.

**Comment by nitriques** [comment]
Hum nothing looks abnormal in this call stack. Could you try this instead:

Before this line https://github.com/DeuxHuitHuit/random_entries_generator/blob/master/vendor/fzaninotto/faker/src/Faker/Factory.php#L16

``` php
var_dump($providerClassName, $provider, $locale);
```

**Comment by animaux** [comment]
That results in:

```
string(22) "Faker\Provider\Address"
string(7) "Address" NULL
string(22) "Faker\Provider\Barcode"
string(7) "Barcode" NULL
string(20) "Faker\Provider\Color"
string(5) "Color" NULL
string(22) "Faker\Provider\Company"
string(7) "Company" NULL
string(23) "Faker\Provider\DateTime"
string(8) "DateTime" NULL
string(19) "Faker\Provider\File"
string(4) "File" NULL
string(20) "Faker\Provider\Image"
string(5) "Image" NULL
string(23) "Faker\Provider\Internet"
string(8) "Internet" NULL
string(20) "Faker\Provider\Lorem"
string(5) "Lorem" NULL
string(28) "Faker\Provider\Miscellaneous"
string(13) "Miscellaneous" NULL
string(22) "Faker\Provider\Payment"
string(7) "Payment" NULL
string(21) "Faker\Provider\Person"
string(6) "Person" NULL
string(26) "Faker\Provider\PhoneNumber"
string(11) "PhoneNumber" NULL
string(19) "Faker\Provider\Text"
string(4) "Text" NULL
```

(plus the beforementioned symphony-error)

**Comment by nitriques** [comment]
This really seems like a Faker issue with your setup... Would you mind creating an issue on their repo ? https://github.com/fzaninotto/Faker/issues

**Comment by animaux** [comment]
I tried the following PHP Versions:
- 5.3.9 (error)
- 5.4.34 (error)
- 5.5.18 (error)
- 5.6.2 (error)

**Comment by nitriques** [comment]
This is crazy. I run 5.3.29 and it does works...

**Comment by aVandalInShorts** [comment]
@nitriques I have the same error on one of our projects. I tested it and the error shows up when I have an Image Upload field. @animaux did you have an Image Upload filed or a Multilangal Image Upload field in your section?

Do you want me to test some other supported fields to know if other ones make the bug?

**Comment by animaux** [comment]
@aVandalInShorts actually I have an `association field` linked to a section containing an `image upload field`. Not sure if `random_entries_generator` creates links in `association field`s.

**Comment by nitriques** [comment]
@animaux 

> Not sure if random_entries_generator creates links in association field

No, it does not. But anybody is welcome to contribute [the proper adapter](https://github.com/DeuxHuitHuit/random_entries_generator/blob/master/lib/class.fieldadapter.php) to do so :)

@aVandalInShorts: I will check this ASAP.

**Comment by animaux** [comment]
@nitriques :)

**Comment by nitriques** [comment]
@animaux Does this fixes the bug for you too ? https://github.com/fzaninotto/Faker/issues/612

**Comment by animaux** [comment]
Fixes the problem for me, great, cheers!

**Comment by nitriques** [comment]
Great!
